---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duah-members-dep
  namespace: duah-apps
  labels:
    app: duah-members
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: duah-members
  template:
    metadata:
      labels:
        app: duah-members
    spec:
      containers:
      - name: duah-members
        image: ghcr.io/denuafhaengige/duah-members:sha-2f62972
        imagePullPolicy: IfNotPresent
        env:
        - name: DUAH_FORCE_DATABASE_SCHEMA_SYNC
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: force-database-schema-sync
        - name: DUAH_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: database-uri
        - name: DUAH_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: redis-host
        - name: DUAH_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duah-shared-secret
              key: redis-password
        - name: DUAH_APP_INSIGHTS_I_KEY
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: application-insights-instrumentation-key
        - name: DUAH_AUTH_ISSUER_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: auth-issuer-base-url
        - name: DUAH_AUTH_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: auth-audience
        - name: DUAH_AUTH_JWKS_URI
          valueFrom:
            configMapKeyRef:
              name: duah-shared-conf
              key: auth-jwks-uri
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: health
          containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 64m
            memory: 128Mi
          requests:
            cpu: 32m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: health
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 30
