apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duah-insights-ingress
  namespace: duah-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: insights.denuafhaengige.dk
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: duah-insights-svc
            port:
              number: 80
  tls:
  - secretName: duah-insights-tls-cert
    hosts:
    - insights.denuafhaengige.dk
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duah-insights-redirect-ingress
  namespace: duah-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://insights.denuafhaengige.dk$request_uri
spec:
  rules:
  - host: insights.xn--denuafhngige-ddb.dk
  - host: insights.denuafhangige.dk
  - host: insights.duah.dk
  tls:
  - secretName: duah-insights-redirect-tls-cert
    hosts:
    - insights.xn--denuafhngige-ddb.dk
    - insights.denuafhangige.dk
    - insights.duah.dk
